### PR TITLE
Added brotli for 18 image

### PR DESCRIPTION
**Pull request by gease**

### CODE REVIEW

**Comment by andypost** [comment]
Nide idea++ to merge and rebuild

For testing purposes it could use 18.0 tag

**Comment by andypost** [comment]
@davidferlay any opinion on versions for images?

**Comment by davidferlay** [comment]
Tested with https://tools.keycdn.com/brotli-test

**Comment by andypost** [comment]
@davidferlay is there any idea how to tag new image? And how to spread?

**Comment by andypost** [comment]
pushed as 1.18.1 and tagged it 1.18 https://hub.docker.com/r/skilldlabs/nginx/tags?page=1&ordering=last_updated

**Pull request merged**
